<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Tests\Tests.csproj" />
      <ProjectReference Include="..\SlowlyEcs.EntitiesFiltering\SlowlyEcs.EntitiesFiltering.csproj" />
      <ProjectReference Include="..\SlowlyEcs.Historicity\SlowlyEcs.Historicity.csproj" />
      <ProjectReference Include="..\SlowlyEcs.Storaging\SlowlyEcs.Storaging.csproj" />
      <ProjectReference Include="..\SlowlyEcs\SlowlyEcs.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
      <PackageReference Include="Leopotam.EcsLite" Version="1.0.1" />
    </ItemGroup>

</Project>
